name: CI/CD para aplicación en Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v2
      
      - name: Crear directorio .ssh y archivo known_hosts
        run: |
          mkdir -p $HOME/.ssh
          touch $HOME/.ssh/known_hosts
      
      - name: Eliminar clave del host SSH
        run: |
          ssh-keygen -R 34.203.206.54 >> $HOME/.ssh/known_hosts

      - name: Iniciar instancia EC2
        run: |
          echo "${{ secrets.CLAVEPRIVADAEC2 }}" > key.pem
          chmod 600 key.pem
          ssh -i key.pem Admin@54.167.10.55 'docker-compose down'
          ssh -i key.pem Admin@54.167.10.55 'rm -rf /ruta/al/repo'
          ssh -i key.pem Admin@54.167.10.55 'git clone https://github.com/fmgarciaa/demo_flow.git'
          ssh -i key.pem Admin@54.167.10.55 'cd /ruta/al/repo && docker-compose up -d'
